/*
 * Twilio - Flex
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.16.1
 * Contact: support@twilio.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/twilio/terraform-provider-twilio/client"
	. "github.com/twilio/terraform-provider-twilio/twilio/common"
	. "github.com/twilio/twilio-go/rest/flex/v1"
)

func ResourceFlexFlows() *schema.Resource {
	return &schema.Resource{
		CreateContext: createFlexFlows,
		ReadContext:   readFlexFlows,
		UpdateContext: updateFlexFlows,
		DeleteContext: deleteFlexFlows,
		Schema: map[string]*schema.Schema{
			"channel_type":                    AsString(SchemaOptional),
			"chat_service_sid":                AsString(SchemaOptional),
			"contact_identity":                AsString(SchemaOptional),
			"enabled":                         AsString(SchemaOptional),
			"friendly_name":                   AsString(SchemaOptional),
			"integration.channel":             AsString(SchemaOptional),
			"integration.creation_on_message": AsString(SchemaOptional),
			"integration.flow_sid":            AsString(SchemaOptional),
			"integration.priority":            AsString(SchemaOptional),
			"integration.retry_count":         AsString(SchemaOptional),
			"integration.timeout":             AsString(SchemaOptional),
			"integration.url":                 AsString(SchemaOptional),
			"integration.workflow_sid":        AsString(SchemaOptional),
			"integration.workspace_sid":       AsString(SchemaOptional),
			"integration_type":                AsString(SchemaOptional),
			"janitor_enabled":                 AsString(SchemaOptional),
			"long_lived":                      AsString(SchemaOptional),
			"account_sid":                     AsString(SchemaComputed),
			"date_created":                    AsString(SchemaComputed),
			"date_updated":                    AsString(SchemaComputed),
			"integration":                     AsString(SchemaComputed),
			"sid":                             AsString(SchemaComputed),
			"url":                             AsString(SchemaComputed),
		},
	}
}

func createFlexFlows(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	params := CreateFlexFlowParams{}
	if err := UnmarshalSchema(&params, d); err != nil {
		return diag.FromErr(err)
	}

	r, err := m.(*client.Config).Client.FlexV1.CreateFlexFlow(&params)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(*r.Sid)
	err = MarshalSchema(d, r)

	if err != nil {
		return diag.FromErr(err)
	}
	return nil
}

func deleteFlexFlows(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {

	sid := d.Get("sid").(string)

	err := m.(*client.Config).Client.FlexV1.DeleteFlexFlow(sid)
	d.SetId("")

	if err != nil {
		return diag.FromErr(err)
	}
	return nil
}

func readFlexFlows(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {

	sid := d.Get("sid").(string)

	r, err := m.(*client.Config).Client.FlexV1.FetchFlexFlow(sid)
	if err != nil {
		return diag.FromErr(err)
	}

	err = MarshalSchema(d, r)

	if err != nil {
		return diag.FromErr(err)
	}
	return nil
}

func updateFlexFlows(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	params := UpdateFlexFlowParams{}
	if err := UnmarshalSchema(&params, d); err != nil {
		return diag.FromErr(err)
	}

	sid := d.Get("sid").(string)

	r, err := m.(*client.Config).Client.FlexV1.UpdateFlexFlow(sid, &params)
	if err != nil {
		return diag.FromErr(err)
	}

	err = MarshalSchema(d, r)

	if err != nil {
		return diag.FromErr(err)
	}
	return nil
}

func ResourceWebChannels() *schema.Resource {
	return &schema.Resource{
		CreateContext: createWebChannels,
		ReadContext:   readWebChannels,
		UpdateContext: updateWebChannels,
		DeleteContext: deleteWebChannels,
		Schema: map[string]*schema.Schema{
			"chat_friendly_name":     AsString(SchemaOptional),
			"chat_unique_name":       AsString(SchemaOptional),
			"customer_friendly_name": AsString(SchemaOptional),
			"flex_flow_sid":          AsString(SchemaOptional),
			"identity":               AsString(SchemaOptional),
			"pre_engagement_data":    AsString(SchemaOptional),
			"account_sid":            AsString(SchemaComputed),
			"date_created":           AsString(SchemaComputed),
			"date_updated":           AsString(SchemaComputed),
			"sid":                    AsString(SchemaComputed),
			"url":                    AsString(SchemaComputed),
		},
	}
}

func createWebChannels(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	params := CreateWebChannelParams{}
	if err := UnmarshalSchema(&params, d); err != nil {
		return diag.FromErr(err)
	}

	r, err := m.(*client.Config).Client.FlexV1.CreateWebChannel(&params)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(*r.Sid)
	err = MarshalSchema(d, r)

	if err != nil {
		return diag.FromErr(err)
	}
	return nil
}

func deleteWebChannels(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {

	sid := d.Get("sid").(string)

	err := m.(*client.Config).Client.FlexV1.DeleteWebChannel(sid)
	d.SetId("")

	if err != nil {
		return diag.FromErr(err)
	}
	return nil
}

func readWebChannels(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {

	sid := d.Get("sid").(string)

	r, err := m.(*client.Config).Client.FlexV1.FetchWebChannel(sid)
	if err != nil {
		return diag.FromErr(err)
	}

	err = MarshalSchema(d, r)

	if err != nil {
		return diag.FromErr(err)
	}
	return nil
}

func updateWebChannels(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	params := UpdateWebChannelParams{}
	if err := UnmarshalSchema(&params, d); err != nil {
		return diag.FromErr(err)
	}

	sid := d.Get("sid").(string)

	r, err := m.(*client.Config).Client.FlexV1.UpdateWebChannel(sid, &params)
	if err != nil {
		return diag.FromErr(err)
	}

	err = MarshalSchema(d, r)

	if err != nil {
		return diag.FromErr(err)
	}
	return nil
}
