language: go
go:
  - '1.15'
  - '1.16'
env:
  - TF_INPUT=false TF_VERSION=1.0.0

# Install dependencies
before_install:
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip
install:
  - make install test
script:
  - echo "$TRAVIS_BRANCH"
  - echo $TRAVIS_PULL_REQUEST
  - if [[ "$TRAVIS_BRANCH" == "main"  ||  "$TRAVIS_BRANCH" == "travis" ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    make testacc TWILIO_ACCOUNT_SID="$ACCOUNT_SID" TWILIO_AUTH_TOKEN="$AUTH_TOKEN";
    fi
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: p48e21acIxzCs/vFcrSGvcv3jk/PnLcI8BaFpek7KE6lFUi+lDOlg3tNJlqBwQh2BKuoFdd4+x5uNcfpm3cl32usPA2K4e5EX6su+yJcrtt18kAt+p9AjrqFqxgKiq3gKCF/Bh8+r+yk8wMgS+WU8Bg2z6cwUqAoy5OcFwkvYu0wbDkFtEwWljXZbWejfEGD5OEq/4aZzM0GNl3DRdVcU7l4p0A3xPLIUJDSjKQ4J3GZSZE64YqHH1ANJergcX6mmMGVIQEHzgAXXBcLanzxTQfySgrrVMJz/xZh4lRJ/EMxMDj9LXFjOgQxJfo5qgPfhgc+s1hFajS0ykcJZW0Y7DnJz42Bjw4HnQayxEoB4/2HBD2Osggkd6mshe86QNzi1Xjd/V+Bs/RfuFHiU63AuAn0F1VHuOyrFu55MDCaJTg5RoWigP3k8cIlIMPAYygdxwB++FwcMiEdnoV9Coh4Lx6d6UNctGUOM22Dlnchn0CXbIb6/jqJA0atM9RvP3O0tcgD1xcN6IfiF55QAkd3E3K1aC+9pvy8UnD6biLf3k6YvaVrO/9ds+KbAhvQhnTnmhc++yAOdb24pbFQQVUYbn6/9nUkFs0Qw5yNP4Smp8dLOL/m9iwSwIqfclVY8GgYzjdDvib7NwWuB2IaHvbNPCsNx7PRtT81RNASoxc/+aM=
