contact_links:
  - name: Twilio Support
    url: https://twilio.com/help/contact
    about: Get Support
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/terraform-provider-twilio+or+twilio+terraform
    about: Ask questions on Stack Overflow
  - name: Documentation
    url: https://github.com/twilio/terraform-provider-twilio/blob/main/twilio/resources/README.md
    about: View Reference Documentation
